apiVersion: v2
name: takserver
description: TAK Server
version: "4.5.0"
type: application

dependencies:
  - name: postgresql
    version: "12.1.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - takserver-backend
      - postgresql
  - name: ignite
    version: "1.2.3"
    repository: "file://./third-party/ignite"
    tags:
      - takserver-backend
      - ignite
  - name: nats-operator
    version: "0.8.3"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    tags:
      - takserver-backend
      - nats-operator
