imagePullSecret: reg-cred
certConfigMapName: cert-migration
coreConfigMapName: core-config
# 'ignite-config' is used for the actual ignite config so the prefix is added
takIgniteConfigMapName: tak-ignite-config

takserver:
  ingress:
    # Note, ingress resources require an ingress controller in the Kubernetes cluster.
    # Note, ingress resources will require ssl passthrough enabled on the ingress controller.
    enabled: false
    api:
      cert:
        annotations: {}
        host: ""
      federationTruststore:
        annotations: {}
        host: ""
      https:
        annotations: {}
        host: ""
    messaging:
      streaming:
        annotations: {}
        host: ""
      fedv1:
        annotations: {}
        host: ""
      fedv2:
        annotations: {}
        host: ""
  config:
    image:
      repository: docker-devtest-local.artifacts.tak.gov/takserver-cluster/takserver-config
      tag: config-provisioned
    replicas: 1
    resources:
      requests:
        cpu: 2
        memory: 1Gi
      limits:
        cpu: 2
        memory: 1Gi
  messaging:
    image:
      repository: docker-devtest-local.artifacts.tak.gov/takserver-cluster/takserver-messaging
      tag: messaging-provisioned
    replicas: 60
    resources:
      requests:
        cpu: 4
        memory: 8Gi
      limits:
        cpu: 4
        memory: 8Gi
  api:
    image:
      repository: docker-devtest-local.artifacts.tak.gov/takserver-cluster/takserver-api
      tag: api-provisioned
    replicas: 30
    resources:
      requests:
        cpu: 4
        memory: 8Gi
      limits:
        cpu: 4
        memory: 8Gi
  plugins:
    enabled: true
    image:
      repository: docker-devtest-local.artifacts.tak.gov/takserver-cluster/takserver-plugins
      tag: plugins-provisioned
    replicas: 1
    resources:
      requests:
        cpu: 4
      limits:
        cpu: 4
  takserverDatabaseSetup:
    image:
      repository: docker-devtest-local.artifacts.tak.gov/takserver-cluster/takserver-database-setup
      tag: takserver-database-setup-provisioned
  limits:
    persistentVolumeClaims: '5'
    requests:
      storage: 100Gi
    storage:
      max: 50Gi
      min: 1Gi
postgresql:
  enabled: false
  image:
    registry: docker.io
    repository: postgis/postgis
    tag: 15-3.3
  configurationConfigMap: postgres-configuration
  postgresqlDatabase: cot

global:
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: postgres

ignite:
  image:
    tag: 2.15.0-jdk11
  serviceAccount:
    name: takserver-ignite

nats-operator:
  image:
    tag: 0.8.3
  cluster:
    auth:
      enabled: false
